### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'appendChild')

### ISSUE THREAD

**Issue by IFaKeEI** [Elements6007/ReturnYoutubeSort#12]
Hi, 

I've downloaded and added the extension today. When I tried it for the first time it didn't work. I looked again into the extension manager and saw this error:
![image_2023-04-15_014623569](https://user-images.githubusercontent.com/70143226/232171430-ec4fddd0-8ce7-40a6-a93b-d95ee5d1303d.png)
Later I've found this error as well: 
![image_2023-04-15_014803806](https://user-images.githubusercontent.com/70143226/232171532-969b1f72-aadd-4976-8ed0-f9d98ef050ed.png)
Any ideas where might be a problem?
Btw. I am using Opera GX as a browser. 

Thank you!

**Comment by Elements6007** [comment]
The first error is probably caused by not refreshing the page after loading the extension. I see you say this happened the first time, did the issue still persist? As for the second error, I have never found the cause of this error. It does not seem to effect anything so currently I am just ignoring it. There should not be a compatibility issue with Opera GX because it is based on chromium but I have never tested on it. 

Also are you using a release?

**Comment by IFaKeEI** [comment]
I've tried reloading the page as well as reloading the whole browser, but none of these worked. I've downloaded the 1.1.0 release as it was the most recent one.

**Comment by IFaKeEI** [comment]
Well I've tried to remove the extension and add it again and it started working... There might have been some problem when I was adding the extension so it failed to work. I guess you can close this Issue thread then. 

Anyways, thank you for reacting quickly and thanks for this extension! Needed it a lot.

**Comment by Elements6007** [comment]
Great! Glad its working now and that you like it!
