### ISSUE TITLE
Too slow, takes awhile to ssee the fist video

### ISSUE THREAD

**Issue by MInecrafterPictures** [Elements6007/ReturnYoutubeSort#23]
**Describe the bug**
I tried the extension but unfortunately, it's not as fast as I wanted to be.
Worst of all, depending of the channel's amount of videos, it can take forever just to find that channel's first video from the channel's videos section.
Also, on unrelated note, it would be nice to add support for not only the shorts section but also the live section as well.

**Version**
Chrome Extension

**Comment by Elements6007** [comment]
Hi, unfortunately there is nothing I can do about this. This extension does not bring back the full functionality of the original sort by oldest. All it does is invert the videos, thus it needs time to load all of them. At this time this is the best I can do since I cannot access the API oldest function. 

As for the support for live section, you should be able to see it as support was added for it in 1.4.0
