### ISSUE TITLE
Unable to load the extension on Firefox

### ISSUE THREAD

**Issue by xinomp** [Elements6007/ReturnYoutubeSort#9]
I get the error "background.Service_Worker is currently disabled" when trying to load the extension. From what I've read, this seems to be a Manifest V3 issue due to Mozilla's implementation of the framework, and that for now "background.scripts" is what's preferable.

I hold no knowledge of this topic so apologies if what I'm saying doesn't make much sense.

**Comment by Elements6007** [comment]
Thanks for bringing this to my attention. I took a look and you are correct, it is an issue with Manifest V3 not being supported in Firefox. I got it to work with a few edits but have not tested its full functionality. Currently this project is only being developed for Chrome since I am the only dev so things might not work correctly in other browsers. I will hopefully add basic FF support in v1.2. In the meanwhile if you want to try you can use Chrome or edit the code yourself. Just two lines need to be changed in `manifest.json`. First change `manifest_version` down to 2 and replace everything in line 8 with `"scripts":  ["background.js"]` 

If you get it to work it would be great if you would report back if it works properly :)

**Comment by Elements6007** [comment]
fixed in `v1.2.0`, closing
